[agent]
  interval = "1s"
  round_interval = true

[[inputs.socket_listener]]
  service_address = "udp://:8094"
  data_format = "influx"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"
